import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SkillTreeProvider } from "./context/SkillTreeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TITANSTAR LEGENDS",
  description: "Generated by jujuhawk and create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SkillTreeProvider>{children}</SkillTreeProvider>
      </body>
    </html>
  );
}
